name: btech_induction_2023
description: IIITD BTech Batch of 2023 Induction App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.1
  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_messaging: ^14.6.5
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  firebase_storage: ^11.2.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/clubs/
    - .env
